name: test

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: add tag
        env:
          TAG_NUMBER: ${{ github.event.pull_request.number }}
          TAG_NAME: ${{ github.event.pull_request.title }}
        run: |
          git tag ${{ env.TAG_NAME }}_#${{ env.TAG_NUMBER }}
          git push origin ${{ env.TAG_NAME }}_#${{ env.TAG_NUMBER }}