name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add tag
        env:
          TAG_NAME: ${{ github.event.pull_request.title }}${{ github.event.pull_request.number }}
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}