name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
#        TAG=${{ github.event.pull_request.title }}
#        git tag $(cat ${TAG})
#        git push origin $(cat ${TAG})
        echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
        git tag $(cat TAG_NAME)
        git push origin $(cat TAG_NAME)