name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          TAG: ${{github.event.pull_request.title}}
      - run: echo ${{ env.TAG }}