name: test

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        TAG=${{ github.event.pull_request.title }}
        echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)"