name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}
      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: git tag v1
      - run: git push origin v1