name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      TAG: ${{github.event.pull_request.title}}
    steps:
      - uses: actions/checkout@v2
      - run: git tag ${TAG}
      - run: git push origin ${TAG}