name: test

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          TAG: ${{github.event.pull_request.title}}
      - run: |
        echo ${{ github.event.pull_request.title }}