name: test

on:
  pull_request:
    types: [ ready_for_review ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: TAG="${{ github.event.pull_request.title }}"
      - run: git tag ${TAG}
      - run: git push origin ${TAG}