name: test

on:
  pull_request:
    types: [ closed ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}
#      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: git tag v2
      - run: git push origin v2