name: add version tag
on:
  push:
    branches:
      - main
jobs:
  release:
    name: add tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG: ${{github.event.pull_request.title}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: |
          git tag v1
          git push origin v1

