name: hogefuga

on:
  pull_request:
    types: [ opened ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get current date time
        id: date_time
        run: echo "::set-output name=now::$(date +'%Y-%m-%dT%H_%M_%SZ')"