name: hogefuga

on:
  pull_request:
    types: [ labeled ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'larastan'
    steps:
      - name: Checkout code
        uses: actions/checkout@master