name: test-gha

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get current date time
        id: date_time
        run: echo "now=${$(date +'%Y-%m-%dT%H_%M_%SZ')}" >> $GITHUB_OUTPUT
      - name: Force failure
        run: exit 1

  send-slack-notification:
    needs: debug
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR author
        id: get-author
        run: echo "author=$(jq -r .pull_request.user.login < $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT

      - name: Get Slack member ID
        id: get-slack-id
        run: |
          author=${{ steps.get-author.outputs.author }}
          slack_id=$(yq e ".${author}" .github/mention-to-slack-config.yml)
          echo "slack_id=${slack_id}" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "test"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <@${{ steps.get-slack-id.outputs.slack_id }}>"
                    }
                  ]
                }
              ]
            }
